import Head from "next/head";
import Image from "next/image";
import { FastForward, Play, Rewind } from "phosphor-react";
import { Container, Controls, Info, Player, SongInfo, TimeContainer, TrackerBar } from "./styles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Music Player</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Player variant="full">
          <SongInfo>
            <Image src="https://images.unsplash.com/photo-1583854765614-8cd9b0bd00f9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=190&q=80" height={190} width={190} alt="" />
            <Info>
              <h1>Acorda Devinho</h1>
              <span>Banda Rocketseat</span>
            </Info>
          </SongInfo>
          <Controls>
            <Rewind size={18} color="#e1e1e6" weight="fill" />
            <Play size={18} color="#e1e1e6" weight="fill" />
            <FastForward size={18} color="#e1e1e6" weight="fill" />
          </Controls>
          <TrackerBar />
          <TimeContainer>
            <span>03:20</span>
            <span>00:12</span>
          </TimeContainer>  
        </Player>
        <Player >
          <SongInfo>
            <Image src="https://images.unsplash.com/photo-1583854765614-8cd9b0bd00f9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=190&q=80" height={190} width={190} alt="" />
            <Info>
              <h1>Acorda Devinho</h1>
              <span>Banda Rocketseat</span>
            </Info>
          </SongInfo>
          <Controls>
            <Rewind size={18} color="#e1e1e6" weight="fill" />
            <Play size={18} color="#e1e1e6" weight="fill" />
            <FastForward size={18} color="#e1e1e6" weight="fill" />
          </Controls>
          <TrackerBar />
          <TimeContainer>
            <span>03:20</span>
            <span>00:12</span>
          </TimeContainer>
        </Player>
        <Player variant="withoutTracker">
          <SongInfo>
            <Image src="https://images.unsplash.com/photo-1583854765614-8cd9b0bd00f9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=190&q=80" height={190} width={190} alt="" />
            <Info>
              <h1>Acorda Devinho</h1>
              <span>Banda Rocketseat</span>
            </Info>
          </SongInfo>
          <Controls>
            <Rewind size={18} color="#e1e1e6" weight="fill" />
            <Play size={18} color="#e1e1e6" weight="fill" />
            <FastForward size={18} color="#e1e1e6" weight="fill" />
          </Controls>
        </Player>
      </Container>

    </>
  )
}
